[phases.setup]
nixPkgs = ['nodejs', 'python3', 'yarn']
aptPkgs = ['build-essential']

[phases.install]
cmd = 'yarn'

[phases.build]
cmds = ['yarn build', 'yarn prisma generate']

[start]
cmd = 'yarn start'  
